---
- hosts: all
  tasks:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#examples
    - name: Create a .ssh directory for root
      become: yes
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: u+rw,g-rwx,o-rwx

    - name: Set public key authentication for root
      become: yes
      vars:
        filename: authorized_keys
      ansible.builtin.copy:
        src:  /home/{{ lookup('env', 'USER') }}/.ssh/{{filename}}
        dest: /root/.ssh/{{filename}}
        mode: u+rw,g-rwx,o-rwx
        remote_src: yes
