---
- hosts: all
  tasks:
    # https://www.codesandnotes.be/2020/01/13/generate-ssh-keys-using-ansible/
    - name: generate SSH key id_rsa
      connection: local
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no
    - name: set up authorized keys for the current user
      authorized_key: user={{ lookup('env', 'USER') }} key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#examples
    - name: Create a .ssh directory for root
      become: yes
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: u+rw,g-rwx,o-rwx

    - name: Set public key authentication for root
      become: yes
      vars:
        filename: authorized_keys
      ansible.builtin.copy:
        src:  /home/{{ lookup('env', 'USER') }}/.ssh/{{filename}}
        dest: /root/.ssh/{{filename}}
        mode: u+rw,g-rwx,o-rwx
        remote_src: yes
