# Creates the non-root user kube.
# Configures the sudoers file to allow the kube user to run sudo commands without a password prompt.
# Adds the public key in your local machine (usually ~/.ssh/id_rsa.pub) to the remote kube user’s authorized key list. 
# This will allow you to SSH into each server as the kube user.
---
- hosts: all
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - acl
        state: latest
        update_cache: true

    - name: create the 'kube' user
      user: name=kube append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'kube' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the kube user
      authorized_key: user=kube key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

- hosts: all
  become: yes
  tasks:
    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

    - name: Set a hostname
      become: yes
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"