- name: install CRI dependencies
  hosts: all
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg2
          - curl
        state: latest
        update_cache: true

    - name: add CRI-O apt-key 1
      vars:
        OS: Debian_11
        VERSION: 1.24
      ansible.builtin.apt_key:
        url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{OS}}/Release.key
        state: present

    - name: add CRI-O apt-key 2
      vars:
        OS: Debian_11
        VERSION: 1.24
      ansible.builtin.apt_key:
        url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{VERSION}}/{{OS}}/Release.key
        state: present

    - name: add CRI-O APT repository 1
      vars:
        OS: Debian_11
        VERSION: 1.24
      apt_repository:
        repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{OS}}/ /
        state: present
        filename: 'devel:kubic:libcontainers:stable.list'

    - name: add CRI-O APT repository 2
      vars:
        OS: Debian_11
        VERSION: 1.24
      apt_repository:
        repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{VERSION}}/{{ OS }}/ /
        state: present
        filename: 'devel:kubic:libcontainers:stable:cri-o:{{VERSION}}.list'

    - name: install cri-o
      ansible.builtin.apt:
        name:
          - cri-o
          - cri-o-runc
        state: present
        update_cache: true

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable service crio
      ansible.builtin.service:
        name: crio
        state: started
        enabled: yes

    - name: Reboot after crio installed
      ansible.builtin.reboot:
        reboot_timeout: 60