---
- hosts: control_plane
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.10.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become_user: ubuntu
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: u+rw,g-rwx,o-rwx

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Tigera Calico operator for Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml >> tigera-operator.txt
      args:
        chdir: $HOME
        creates: tigera-operator.txt

    - name: install Tigera Calico for Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml >> custom-resources.txt
      args:
        chdir: $HOME
        creates: custom-resources.txt
